package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AsientosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientosAllPropertiesEquals(Asientos expected, Asientos actual) {
        assertAsientosAutoGeneratedPropertiesEquals(expected, actual);
        assertAsientosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientosAllUpdatablePropertiesEquals(Asientos expected, Asientos actual) {
        assertAsientosUpdatableFieldsEquals(expected, actual);
        assertAsientosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientosAutoGeneratedPropertiesEquals(Asientos expected, Asientos actual) {
        assertThat(actual)
            .as("Verify Asientos auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientosUpdatableFieldsEquals(Asientos expected, Asientos actual) {
        assertThat(actual)
            .as("Verify Asientos relevant properties")
            .satisfies(a -> assertThat(a.getFila()).as("check fila").isEqualTo(expected.getFila()))
            .satisfies(a -> assertThat(a.getColumna()).as("check columna").isEqualTo(expected.getColumna()))
            .satisfies(a -> assertThat(a.getPersona()).as("check persona").isEqualTo(expected.getPersona()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsientosUpdatableRelationshipsEquals(Asientos expected, Asientos actual) {
        assertThat(actual)
            .as("Verify Asientos relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()))
            .satisfies(a -> assertThat(a.getVenta()).as("check venta").isEqualTo(expected.getVenta()))
            .satisfies(a -> assertThat(a.getSesion()).as("check sesion").isEqualTo(expected.getSesion()));
    }
}
