package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllPropertiesEquals(Evento expected, Evento actual) {
        assertEventoAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllUpdatablePropertiesEquals(Evento expected, Evento actual) {
        assertEventoUpdatableFieldsEquals(expected, actual);
        assertEventoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAutoGeneratedPropertiesEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableFieldsEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getResumen()).as("check resumen").isEqualTo(expected.getResumen()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a -> assertThat(a.getFilaAsientos()).as("check filaAsientos").isEqualTo(expected.getFilaAsientos()))
            .satisfies(a -> assertThat(a.getColumnaAsientos()).as("check columnaAsientos").isEqualTo(expected.getColumnaAsientos()))
            .satisfies(a -> assertThat(a.getPrecioEntrada()).as("check precioEntrada").isEqualTo(expected.getPrecioEntrada()))
            .satisfies(a -> assertThat(a.getEventoTipoNombre()).as("check eventoTipoNombre").isEqualTo(expected.getEventoTipoNombre()))
            .satisfies(a ->
                assertThat(a.getEventoTipoDescripcion()).as("check eventoTipoDescripcion").isEqualTo(expected.getEventoTipoDescripcion())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a ->
                assertThat(a.getUltimaActualizacion()).as("check ultimaActualizacion").isEqualTo(expected.getUltimaActualizacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableRelationshipsEquals(Evento expected, Evento actual) {
        // empty method
    }
}
