package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IntegrantesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrantesAllPropertiesEquals(Integrantes expected, Integrantes actual) {
        assertIntegrantesAutoGeneratedPropertiesEquals(expected, actual);
        assertIntegrantesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrantesAllUpdatablePropertiesEquals(Integrantes expected, Integrantes actual) {
        assertIntegrantesUpdatableFieldsEquals(expected, actual);
        assertIntegrantesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrantesAutoGeneratedPropertiesEquals(Integrantes expected, Integrantes actual) {
        assertThat(actual)
            .as("Verify Integrantes auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrantesUpdatableFieldsEquals(Integrantes expected, Integrantes actual) {
        assertThat(actual)
            .as("Verify Integrantes relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getIdentificacion()).as("check identificacion").isEqualTo(expected.getIdentificacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIntegrantesUpdatableRelationshipsEquals(Integrantes expected, Integrantes actual) {
        assertThat(actual)
            .as("Verify Integrantes relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
