package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SesionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionAllPropertiesEquals(Sesion expected, Sesion actual) {
        assertSesionAutoGeneratedPropertiesEquals(expected, actual);
        assertSesionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionAllUpdatablePropertiesEquals(Sesion expected, Sesion actual) {
        assertSesionUpdatableFieldsEquals(expected, actual);
        assertSesionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionAutoGeneratedPropertiesEquals(Sesion expected, Sesion actual) {
        assertThat(actual)
            .as("Verify Sesion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUpdatableFieldsEquals(Sesion expected, Sesion actual) {
        assertThat(actual)
            .as("Verify Sesion relevant properties")
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getEstadoFlujo()).as("check estadoFlujo").isEqualTo(expected.getEstadoFlujo()))
            .satisfies(a -> assertThat(a.getEventoSeleccionado()).as("check eventoSeleccionado").isEqualTo(expected.getEventoSeleccionado())
            )
            .satisfies(a ->
                assertThat(a.getAsientosSeleccionados()).as("check asientosSeleccionados").isEqualTo(expected.getAsientosSeleccionados())
            )
            .satisfies(a -> assertThat(a.getUltimaActividad()).as("check ultimaActividad").isEqualTo(expected.getUltimaActividad()))
            .satisfies(a -> assertThat(a.getExpiraEn()).as("check expiraEn").isEqualTo(expected.getExpiraEn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUpdatableRelationshipsEquals(Sesion expected, Sesion actual) {
        // empty method
    }
}
